#!/bin/bash

PLANTUML_VERSION=8047

echo "Downloading sources"
wget http://downloads.sourceforge.net/project/plantuml/plantuml-asl-$PLANTUML_VERSION.tar.gz

echo "Cleaning "
rm -rf src/main/java/net
rm -rf src/main/java/h
rm -rf src/main/java/gen
rm -rf src/main/java/smetana

echo "Unpackaging the archive"
tar -xzf plantuml-asl-$PLANTUML_VERSION.tar.gz
mv src/net src/main/java
mv src/gen src/main/java
mv src/smetana src/main/java
mv src/h src/main/java

echo "Removing unneeded files from archive."
rm README
rm build.xml
rm plantuml-asl-$PLANTUML_VERSION.tar.gz
rm src/main/java/net/sourceforge/plantuml/ant/PlantUmlTask.java

# https://github.com/Banno/sbt-plantuml-plugin/issues/7
rm src/main/java/net/sourceforge/plantuml/eggs/PSystemMemorial.java
rm src/main/java/net/sourceforge/plantuml/eggs/PSystemMemorialFactory.java
sed -i '' '/PSystemMemorialFactory/d' src/main/java/net/sourceforge/plantuml/PSystemBuilder.java

rm -rf src/sprites

echo "Converting dos line endings to linux"
find src/main/java/net -name "*.java" | xargs dos2unix -q

echo "All Done!"
